### ISSUE TITLE
Typo in "/chart-data" (index.html) means graph doesn't find data stream

### ISSUE THREAD

**Issue by bibbygoodwin** [roniemartinez/real-time-charts-with-flask#1]
Hi there,

Thanks for writing this clear example. I noticed that running the code doesn't actually have the intended effect: the graph doesn't update, though if you navigate to /chart_data you can see the JSON data being written.

The reason is you have a small inconsistency between the flask app.py and the index.html template - you go from an underscore to a hyphen in "/chart-data".

Cheers!

**Comment by roniemartinez** [comment]
I believe I am using it the correct way.

If you look at the `@route` decorator on this line, I am using `/chart-data`: https://github.com/roniemartinez/real-time-charts-with-flask/blob/eca3013cb0f5ab3387266e635353b22b563c36ab/application.py#L24

If you look at the html file, I am using the same URL (`/chart-data`): https://github.com/roniemartinez/real-time-charts-with-flask/blob/eca3013cb0f5ab3387266e635353b22b563c36ab/templates/index.html#L78

And if you search the whole repository, the only usage of underscore is for the function used by the route: https://github.com/roniemartinez/real-time-charts-with-flask/search?q=chart_data&unscoped_q=chart_data

There's nothing to fix here. There could be something wrong with your setup.
