### ISSUE TITLE
Asking

### ISSUE THREAD

**Issue by FunGuardian** [roniemartinez/real-time-charts-with-flask#2]
Hi Ronnie, how r u?

i wanna ask about this code below 

```
@application.route('/chart-data')
def chart_data():
    def generate_random_data():
        while True:
            json_data = json.dumps(
                {'time': datetime.now().strftime('%Y-%m-%d %H:%M:%S'), 'value': random.random() * 100})
            yield f"data:{json_data}\n\n"
            time.sleep(1)

    return Response(generate_random_data(), mimetype='text/event-stream')
```

why you make 2 method/function (chart_data() & generate_random_data()) in this route?

**Comment by roniemartinez** [comment]
@FunGuardian,
In order for SSE to work in Flask, you should pass a generator/iterator to `Response()`. In this example, `chart_data()` is the view for the Flask route `/chart-data` while `generate_random_data()` is a generator. 

`generate_random_data()` can be any generator/iterator that produces the data for the SSE. It can be simplified like this:

```python
@application.route('/chart-data')
def chart_data():
    return Response(data_generator(), mimetype='text/event-stream')
```
